version: '3'
services:
  postgres:
    restart: always
    container_name: nest-wetelo-postgres
    image: postgres:15.1
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    restart: always
    container_name: nest_wetelo_pgadmin
    image: dpage/pgadmin4:6.18
    ports:
      - '8080:80'
    env_file:
      - .env
    networks:
      - postgres

volumes:
  data_postgres:
  data_pgadmin:

networks:
  postgres:
    driver: bridge
